### PR TITLE
Task 7

### PR DESCRIPTION
**Pull request by zsummy**
6/6
FE: https://d24vcleeydf9fi.cloudfront.net
FE PR: https://github.com/zsummy/nodejs-aws-fe/pull/5
FE requires `authorization_token` to be set in localStorage

```
> Buffer.from('zsummy:TEST_PASSWORD').toString('base64')
'enN1bW15OlRFU1RfUEFTU1dPUkQ='
```

Import file example:
title,description,price,count
some title,some description,12.34,5

### CODE REVIEW

**Comment by NikaOrl** [comment]
Hi! Well, I tried it in the incognito window with nothing set in localStorage and there was 200 status so the authorization doesn't work for the moment
image
Ping me if you fix it

**Comment by NikaOrl** [comment]
1/6 for now :(

**Comment by zsummy** [comment]
@NikaOrl 
Please read the PR description :)
UI sets 2 localstorage items: login=zsummy, password=TEST_PASSWORD
If you change nothing, UI will take those values and you'll get 200.
If you change login or password, you'll get 403
You may also test direct url in browser/postman/whatever: https://319e3qh7b0.execute-api.eu-west-1.amazonaws.com/dev/import?name=file.csv - you'll get 401

**Comment by zsummy** [comment]
@NikaOrl 
UI sets localstorage items every time on startup, just for convenience. You may observe `Authorization` header in the request.

**Comment by NikaOrl** [comment]
@zsummy please, read the task description 
This lambda should have at least **one environment variable with credentials: {yours_github_account_login}=TEST_PASSWORD**
...
Request from the client application to the /import path of the import-service should have Basic Authorization header: Authorization: Basic authorization_token where authorization_token is equal base64-encoded({yours_github_account_login}:TEST_PASSWORD) (For example, Authorization: Basic sGLzdRxvZmw0ZXs0UGFzcw==) **Client should get authorization_token value from browser localStorage**

So in .env you should have sth like
zsummy=TEST_PASSWORD

And that is exactly what I should test
image

Ping me if you make it according to the description

**Comment by NikaOrl** [comment]
4/6 for now but ready to check the third and the additional task

**Comment by zsummy** [comment]
@NikaOrl 
That was made just for convenience, I mean setting login+password. Now it's changed to grab 'authorization_token' from localStorage. Please check if you have time.

**Comment by zsummy** [comment]
@NikaOrl 
Additional task is implemented:
Client application should display alerts for the responses in 401 and 403 HTTP statuses. This behavior should be added to the nodejs-aws-fe-main/src/index.tsx file
https://github.com/zsummy/nodejs-aws-fe/pull/5/files#diff-0b5adbfe7b36e4ae2f479291e20152e33e940f7f265162d77f40f6bdb5da7405

Anyway thank you for your patience :)

**Comment by NikaOrl** [comment]
Great, tested 
6/6 
Guess, you forgot to push last changes

**Pull request merged**
